### ISSUE TITLE
swal is not defined

### ISSUE THREAD

**Issue by iMomen** [tushariscoolster/ng-sweet-alert#1]
I try to fire the alert but it shown up this message on console 
"swal is not defined"

**Comment by tushar-borole** [comment]
@iMomen  You need to import sweet alert js and css,
https://github.com/t4t5/sweetalert

**Comment by iMomen** [comment]
@tushariscoolster thanks .. i solve it :) :+1:

**Comment by deth8888** [comment]
oh no! even if  have the css and js still swal not defined

**Comment by tushar-borole** [comment]
@deth8888  have you loaded js and css before directive is loaded

**Comment by deth8888** [comment]
yes i put it on the head of my html
