### ISSUE TITLE
SweetAlert service issue

### ISSUE THREAD

**Issue by chyupa** [tushariscoolster/ng-sweet-alert#12]
You can't call another SweetAlert function inside a SweetAlert promise.
See [plunker](https://plnkr.co/edit/D99aXauVbIuQvBbCV8lh)

It would be great if you could show a SweetAlert success when a user clicked on the confirm button from SweetAlert confirm.

**Comment by Daymannovaes** [comment]
You just have to add the option `closeOnConfirm: false` in the first alert. This is teached in the page of sweet-alert: http://t4t5.github.io/sweetalert/

**Comment by tushar-borole** [comment]
@chyupa  i will consider this issues as solved
