### ISSUE TITLE
Can we have close icon on the alert.

### ISSUE THREAD

**Issue by anujmayank** [tushariscoolster/ng-sweet-alert#13]
Can we have close icon in the alert such as we have in bootstrap modal.

**Comment by tushar-borole** [comment]
@anujmayank  not unless you edit the core javascripte of sweet alert, or you can do dom manipulation on modal box open event

**Comment by anujmayank** [comment]
ok..I will try that one more question.....can we have three buttons on the alert?

**Comment by tushar-borole** [comment]
@anujmayank in https://limonte.github.io/sweetalert2/
You have 
onOpen  null    Function to run when modal opens, provides modal DOM element as first param.

On that event you have to append as much button as you can

Cheers

**Comment by limonte** [comment]
> https://limonte.github.io/sweetalert2/

this link is outdated, here's the correct one https://sweetalert2.github.io/
