### ISSUE TITLE
Close Alert Programatically

### ISSUE THREAD

**Issue by tyrus1235** [tushariscoolster/ng-sweet-alert#19]
The normal sweetalert has a "close()" function you can call to force the alert to close itself. Is it possible to add this feature in ng-sweet-alert as well or is there any alternatives for that same behavior?

To elaborate: I have a \<a\> tag inside the message of an alert and I want to close the alert when the user clicks on it and gets redirected to another view (currently the alert remains open and the user has to manually click "Ok" to close it after being redirected).

**Comment by tyrus1235** [comment]
Nevermind, you can close it using the original swal.close() function.

**Comment by tushar-borole** [comment]
@tyrus1235  Thank you so much, u was busy in my work so was not able to look into it
