### ISSUE TITLE
Feature request: Use alerts as native JS functions

### ISSUE THREAD

**Issue by narkissbv** [tushariscoolster/ng-sweet-alert#2]
Wanted to use the ng-sweet-alert like native confirm / alert dialog messages via JS, and not via HTML attributes, something like:
return confirm("Are you sure?");

Also we should be using "promises" to make sure the application waits for the response from the confirm dialog box, and executes the proper code according to the button pressed.

This will help us maintain our already-existing alert / confirm functions, and make them prettier with SweetAlert, and using AngularJS.

**Comment by tushar-borole** [comment]
@narkissbv  Please update readme
