### ISSUE TITLE
Lack of showLoaderOnConfirm 

### ISSUE THREAD

**Issue by OrgmSoftware** [tushariscoolster/ng-sweet-alert#7]
THat would be amazing if the angular version could actually lock the buttons and show that moving '...' on the OK button after confirm.

The native bootstrap version of sweet alert has this feature, so it would be amazing if I could do it with angular.

**Comment by tushar-borole** [comment]
@MateusDmn thanks for your suggesion, will spend time on this in weekend , pull request is also most welcome :)

**Comment by tushar-borole** [comment]
@MateusDmn  I looked into this problem. it is so easy to do with same directive. http://plnkr.co/edit/MmjrHEBdGcUur7n1psNE?p=preview on ajax success you have to just call          `swal("Ajax request finished!");` Do let me know :)

**Comment by tushar-borole** [comment]
@MateusDmn  should i consider this issue done?

**Comment by yazeedb** [comment]
Hello @MateusDmn! 

As @tushariscoolster mentioned, this functionality is easy to accomplish within the directive.

``` javascript
 $scope.sweet.option = {
    title: "Ajax request example",
    text: "Submit to run ajax request",
    type: "info",
    showCancelButton: true,
    closeOnConfirm: false,
    showLoaderOnConfirm: true
}
```

``` javascript
$scope.checkConfirm = function () {
    setTimeout(function () {
        swal('Success!', 'AJAX request success!', 'success'); 
    }, 2000);
}
```

Setting `showLoaderOnConfirm` to true will display the loader, and setting `closeOnConfirm` to false will stop the alert from initially closing. Then you simply invoke `swal()`, which will replace the previous alert with a new one and return your AJAX success message.

Hope this helps!

**Comment by tushar-borole** [comment]
@yazeedb  Thank you for explaining
I am considering this issue as done now and closing it
